sudo: required

services:
  - docker

before_install:
  - docker build -t aramadsanar/client-tester -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true aramadsanar/client-tester npm run test

after_build:
  - docker build -t aramadsanar/multi-client ./client
  - docker build -t aramadsanar/multi-nginx ./nginx
  - docker build -t aramadsanar/multi-server ./servet
  - docker build -t aramadsanar/multi-worker ./worker

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-2
  app: multi-docker
  env: Multi-docker-env
  bucket_name: elasticbeanstalk-ap-southeast-2-675683048575
  bucket_path: multi-docker
  on:
    branch: main
  access_id_key: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
