name: Deploy Multidocker
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t aramadsanar/client-tester -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true aramadsanar/client-tester npm run test

      - run: docker build -t aramadsanar/multi-client ./client
      - run: docker build -t aramadsanar/multi-nginx ./nginx
      - run: docker build -t aramadsanar/multi-server ./servet
      - run: docker build -t aramadsanar/multi-worker ./worker

      - run: docker push  aramadsanar/multi-client
      - run: docker push  aramadsanar/multi-nginx
      - run: docker push  aramadsanar/multi-server
      - run: docker push  aramadsanar/multi-worker
